# render.yaml
services:
  # Frontend service
  - type: web
    name: bjjtv
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://bjjtv.onrender.com,https://bjjtv.com.br

  # Backend service
  - type: web
    name: bjjtv
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://mdb_h36p_user:lMv3mbgwo4Obc8UkCevku7CJfLBRwihL@dpg-cu5etft6l47c73dmmlc0-a.oregon-postgres.render.com/mdb_h36p
      - key: SECRET_KEY
        value: chave_super_secreta_rnbjjtv
      - key: CORS_ORIGINS
        value: https://bjjtv.onrender.com,https://bjjtv.com.br,http://localhost:3000
      - key: PYTHON_VERSION
        value: 3.11.7